# Generated by Django 4.1 on 2024-08-13 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=50)),
                ('crops', models.JSONField()),
                ('date_harvested', models.DateField(default=datetime.datetime(2024, 8, 13, 20, 55, 52, 874155))),
            ],
        ),
    ]
