# Generated by Django 4.1 on 2024-09-20 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accounting', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Advertising', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Bank_Charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cleaning', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Borehole_Implements', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Tractor_Hiring', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Tomato_Trellising_Twine', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Consulting_Fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Council_Unit_Tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Medicines_Vet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fuels_Oils', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Spraying_Chemicals', models.DecimalField(decimal_places=2, max_digits=10)),
                ('General_Expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Insurance_Licenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stockfeeds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MotorVehicle_Maintenance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Tractor_Repairs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Seeds_Tomatoes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Seeds_Beans', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Salaries_Wages', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Security', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fertiliser', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Telephones_Fax_Internet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Training', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Travelling', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Staff_Welfare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Loan_Repayment', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='harvest',
            name='date_harvested',
            field=models.DateField(default=datetime.datetime(2024, 9, 20, 17, 30, 6, 260333)),
        ),
    ]
