# Generated by Django 4.1 on 2024-09-24 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_expensecategory_expenseentry_delete_harvest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='expenseentry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='expenseentry',
            name='description',
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='category_name',
            field=models.CharField(default=15, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='category',
            field=models.CharField(choices=[('Accounting', 'Accounting'), ('Advertising', 'Advertising'), ('Bank Charges', 'Bank Charges'), ('Cleaning', 'Cleaning'), ('Borehole Implements', 'Borehole Implements'), ('Tractor Hiring', 'Tractor Hiring'), ('Tomato Trellising Twine', 'Tomato Trellising Twine'), ('Consulting Fees', 'Consulting Fees'), ('Council Unit Tax', 'Council Unit Tax'), ('Medicines Vet', 'Medicines Vet'), ('Fuels Oils', 'Fuels Oils'), ('Spraying Chemicals', 'Spraying Chemicals'), ('General Expenses', 'General Expenses'), ('Insurance Licenses', 'Insurance Licenses'), ('Stockfeeds', 'Stockfeeds'), ('MotorVehicle Maintenance', 'MotorVehicle Maintenance'), ('Tractor Repairs', 'Tractor Repairs'), ('Seeds Tomatoes', 'Seeds Tomatoes'), ('Seeds Beans', 'Seeds Beans'), ('Salaries Wages', 'Salaries Wages'), ('Security', 'Security'), ('Fertiliser', 'Fertiliser'), ('Telephones Fax Internet', 'Telephones Fax Internet'), ('Training', 'Training'), ('Travelling', 'Travelling'), ('Staff Welfare', 'Staff Welfare'), ('Loan Repayment', 'Loan Repayment')], max_length=50),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='expense',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='store.expense'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='expense',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='expense_entries', to='store.expense'),
            preserve_default=False,
        ),
    ]
